name: Build Native Flutter Android APK

on:
  push:
    branches:
      - main
      - master
      - koushik
  workflow_dispatch:

jobs:
  build:
    name: Build Native Android Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java 17 (Required for Android Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --debug --android-skip-build-dependency-validation

      - name: Upload Native Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kiwi-music-android-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7
